# vi: set ft=ruby :

NUM_DAEMONS = ENV["NUM_DAEMONS"] ? ENV["NUM_DAEMONS"].to_i : 1

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", type: "dhcp"
  config.vm.box = "centos/7"

  (0..NUM_DAEMONS - 1).each do |i|
    config.vm.define "mon#{i}" do |mon|
      mon.vm.hostname = "mon#{i}"
    end
    config.vm.define "mgr#{i}" do |mgr|
      mgr.vm.hostname = "mgr#{i}"
    end
    config.vm.define "osd#{i}" do |osd|
      osd.vm.hostname = "osd#{i}"
      osd.vm.provider :libvirt do |libvirt|
        libvirt.storage :file, :size => '5G'
        libvirt.storage :file, :size => '5G'
        libvirt.storage :file, :size => '5G'
      end
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo cp -r /home/vagrant/.ssh /root/.ssh
    sudo yum install -y python36 podman ceph lvm2
  SHELL
end
